### ISSUE TITLE
Innehåll i flertalet genpaneler går ej att se på sidan http://cmdscout2.lund.skane.se/panels. Felmeddelande är "Internal Server Error

### ISSUE THREAD

**Issue by ViktorHy** [Clinical-Genomics-Lund/nextflow_wgs#39]
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

**Comment by bjhall** [comment]
Old problem that I never got around to fix...

The reason is that the panels were imported from an older version of scout where panels did mot have maintainers. If a panel is missing the "maintainers" field in the database, this crash happens. 

A workaround is to add `"maintainers": [ ] ` to all panels that lack the field. The correct fix is to patch Scout to check if it's defined before the for-loop...
